import Head from "next/head";
import Image from "next/image";
import hamburger from "../../public/hamburger.svg";
import { Menu, Transition } from "@headlessui/react";
import { Fragment } from "react";

const Coba = () => {
  return (
    <div>
      <Head>
        <title>Home - Arsha Setya Pradita</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icoku.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
    </div>
  );
};

export default Coba;
