import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import email from "../../public/icons8-gmail.svg";
import github from "../../public/icons8-github.svg";
import linkedin from "../../public/icons8-linkedin.svg";
import hamburger from "../../public/hamburger.svg";
import profile from "../../public/profile.png";
import { Menu, Transition } from "@headlessui/react";
import { Fragment } from "react";

const about = () => {
  return (
    <div>
      <Head>
        <title>About - Arsha Setya Pradita</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icoku.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div
        className="flex flex-col w-screen h-screen md:flex md:flex-row md:divide-slate-600
          md:divide-x md:divide-dashed lg:flex xl:flex "
      >
        <div
          className="px-5 py-3 w-full flex absolute justify-between border-dashed border-b border-b-gray-500 md:border-none md:w-4/12 md:py-10 md:relative md
        :h-screen md:flex md:flex-col xl:px-20 lg:px-10 md:px-8"
        >
          <Link href="/">
            <div className="font-sans font-bold text-base leading-4 md:font-bold cursor-pointer md:text-2xl w-2/12 md:leading-5 text-black xl:w-4/12 lg:w-3/12 md:w-3/12">
              ARSHA SETYA PRADITA
            </div>
          </Link>
          <div className="hidden md:block">
            <Link href="/">
              <h1 className="font-sans font-normal text-lg text-gray-400 hover:text-black md:text-base lg:text-lg">
                Back to home
              </h1>
            </Link>
          </div>
          <div className="hidden md:block">
            <div className="flex md:flex">
              <div className="mr-2">
                <a href="mailto:arshapradita@gmail.com" target="blank">
                  <Image src={email}></Image>
                </a>
              </div>
              <div className="mr-2">
                <a
                  href="https://www.linkedin.com/in/arsha-setya-pradita/"
                  target="blank"
                >
                  <Image src={linkedin}></Image>
                </a>
              </div>
              <div>
                <a href="https://github.com/arshapradita" target="blank">
                  <Image src={github}></Image>
                </a>
              </div>
            </div>
            <h1 className="font-sans font-normal text-lg text-gray-400 md:text-base lg:text-lg">
              Designed & Built by Arsha
            </h1>
          </div>
          <div className="h-8 w-8 my-auto rounded-lg border-gray-400 border-solid border-2 md:hidden">
            <Menu as="div">
              <div>
                <Menu.Button>
                  <Image src={hamburger}></Image>
                </Menu.Button>
              </div>
              <Transition
                as={Fragment}
                enter="transition ease-out duration-100"
                enterFrom="transform opacity-0 scale-95"
                enterTo="transform opacity-100 scale-100"
                leave="transition ease-in duration-75"
                leaveFrom="transform opacity-100 scale-100"
                leaveTo="transform opacity-0 scale-95"
              >
                <Menu.Items className="absolute z-10 right-4 mt-2 w-11/12 origin-top-right divide-y divide-gray-100 rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none">
                  <div className="px-1 py-1 hover:bg-gray-400">
                    <Menu.Item>
                      {({ active }) => (
                        <Link href="/">
                          <button
                            className={`${
                              active
                                ? "bg-gray-400 text-white"
                                : "text-gray-900"
                            } group w-full items-center rounded-md px-2 py-2 text-sm text-center`}
                          >
                            Back to home
                          </button>
                        </Link>
                      )}
                    </Menu.Item>
                  </div>
                </Menu.Items>
              </Transition>
            </Menu>
          </div>
        </div>
        <div className="h-full w-full relative z-0 overflow-x-hidden top-20 px-5 md:top-0 md:py-10 md:w-8/12">
          <div>
            <div className="w-1/2 md:w-4/12 xl:w-3/12">
              <Image src={profile}></Image>
            </div>
            <h1 className="font-sans font-medium text-base md:text-lg text-black leading-10">
              Arsha Setya Pradita / Front-end Developer
            </h1>
            <p className="font-sans font-normal text-sm text-justify md:text-base text-gray-500 mb-5 ">
              Born in kediri and now live in sidoarjo. Currently working
              freelance for website creation. Im now graduated with a bachelors
              degree in informatics from Muhammadiyah University of Sidoarjo. In
              my spare time, i like sleeping, taking photos and learning the
              latest technology. Field of interests : Front-end developer, UI/UX
              Design and Administration.
            </p>
          </div>
          <div>
            <h1 className="font-sans font-medium text-base md:text-lg text-black mb-1">
              Experience
            </h1>
            <hr></hr>
            <p className="font-sans font-normal text-sm md:text-base text-justify text-gray-500 mt-3 mb-3">
              <span className="font-sans font-medium text-sm md:text-base text-gray-500 mb-1">
                IT Staff - PT Safra Asia Berjaya
              </span>{" "}
              <br></br>( Mey 2020 - June 2021 )
            </p>
            <ul className="list-outside list-disc px-5">
              <li className="font-sans font-normal text-sm md:text-base text-left text-gray-500">
                Built an e-commerce website by selling 9 products owned by the
                company
              </li>
              <li className="font-sans font-normal text-sm md:text-base text-left text-gray-500">
                Maintained the company's e-commerce website as well as hardware
                such as printers and computers in the office
              </li>
              <li className="font-sans font-normal text-sm md:text-base text-left text-gray-500">
                Help make a report on goods that have been sold on the company's
                e-commerce website
              </li>
            </ul>
            <p className="font-sans font-normal text-sm md:text-base text-justify text-gray-500 mt-3 mb-3">
              <span className="font-sans font-medium text-sm md:text-base text-gray-500 mb-1">
                Internship - Dinas Perumahan Rakyat, Kawasan Permukiman dan
                Cipta Karya Provinsi Jawa Timur
              </span>{" "}
              <br></br>( March 2019 - May 2019 )
            </p>
            <ul className="list-outside list-disc px-5 mb-5">
              <li className="font-sans font-normal text-sm text-left md:text-base text-gray-500">
                Built a website to display direct and indirect shopping charts
                in 5-sector fields
              </li>
              <li className="font-sans font-normal text-sm text-left md:text-base text-gray-500">
                Collected direct and indirect expenditure data in 5-sector
                sectors
              </li>
              <li className="font-sans font-normal text-sm text-left md:text-base text-gray-500">
                Assisted recap data regarding the recapitulation of the proposed
                APBD program in 2019
              </li>
            </ul>
          </div>
          <div>
            <h1 className="font-sans font-medium text-base md:text-lg text-black mb-1">
              Technical Skill
            </h1>
            <hr></hr>
            <p className="font-sans font-normal text-sm md:text-base text-left text-gray-500 mt-3 mb-3">
              <span className="font-sans font-medium text-sm md:text-base text-gray-500 mb-1">
                Languages :
              </span>{" "}
              JavaScript, HTML, CSS, PHP
              <br></br>{" "}
              <span className="font-sans font-medium text-sm md:text-base text-gray-500 mb-1">
                Frameworks :
              </span>{" "}
              React (Next), Laravel
              <br></br>
              <span className="font-sans font-medium text-sm md:text-base text-gray-500 mb-1">
                Developer Tools :
              </span>{" "}
              Git, Tailwind, Bootstrap, SASS, Webpack
              <br></br>
              <span className="font-sans font-medium text-sm md:text-base text-gray-500 mb-1">
                Relevant Skills :
              </span>{" "}
              Web Performance, Web Accessibility, Clean Code, REST API, JSON
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default about;
