import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import email from "../public/icons8-gmail.svg";
import github from "../public/icons8-github.svg";
import linkedin from "../public/icons8-linkedin.svg";
import hamburger from "../public/hamburger.svg";
import { Menu, Transition } from "@headlessui/react";
import { Fragment } from "react";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home - Arsha Setya Pradita</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icoku.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="flex flex-col w-screen h-screen md:flex md:flex-row lg:flex xl:flex ">
        <div className="px-5 py-3 w-full flex absolute md:w-4/12 md:py-10 md:relative md:h-screen md:flex md:flex-col justify-between xl:px-20 lg:px-10 md:px-8">
          <div className="font-sans font-bold text-base leading-4 md:font-bold md:text-2xl w-2/12 md:leading-5 text-black xl:w-4/12 lg:w-3/12 md:w-3/12">
            ARSHA SETYA PRADITA
          </div>
          <div className="hidden md:block">
            <Link href="/about">
              <h1 className="font-sans font-normal text-lg text-gray-400 hover:text-black cursor-pointer md:text-base lg:text-lg">
                About
              </h1>
            </Link>
            <Link href="/project">
              <h1 className="font-sans font-normal text-lg text-gray-400 hover:text-black cursor-pointer md:text-base lg:text-lg">
                Project
              </h1>
            </Link>
            <Link href="/contact">
              <h1 className="font-sans font-normal text-lg text-gray-400 hover:text-black cursor-pointer md:text-base lg:text-lg">
                Contact
              </h1>
            </Link>
          </div>
          <div className="hidden md:block">
            <div className="flex md:flex">
              <div className="mr-2">
                <a href="mailto:arshapradita@gmail.com" target="blank">
                  <Image src={email}></Image>
                </a>
              </div>
              <div className="mr-2">
                <a
                  href="https://www.linkedin.com/in/arsha-setya-pradita/"
                  target="blank"
                >
                  <Image src={linkedin}></Image>
                </a>
              </div>
              <div>
                <a href="https://github.com/arshapradita" target="blank">
                  <Image src={github}></Image>
                </a>
              </div>
            </div>
            <h1 className="font-sans font-normal text-lg text-gray-400 md:text-base lg:text-lg">
              Designed & Built by Arsha
            </h1>
          </div>
          <div className="h-8 w-8 my-auto rounded-lg border-gray-400 border-solid border-2 md:hidden">
            <Menu as="div">
              <div>
                <Menu.Button>
                  <Image src={hamburger}></Image>
                </Menu.Button>
              </div>
              <Transition
                as={Fragment}
                enter="transition ease-out duration-100"
                enterFrom="transform opacity-0 scale-95"
                enterTo="transform opacity-100 scale-100"
                leave="transition ease-in duration-75"
                leaveFrom="transform opacity-100 scale-100"
                leaveTo="transform opacity-0 scale-95"
              >
                <Menu.Items className="absolute right-4 mt-2 w-11/12 origin-top-right divide-y divide-gray-100 rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none">
                  <div className="px-1 py-1 hover:bg-gray-400">
                    <Menu.Item>
                      {({ active }) => (
                        <Link href="/about">
                          <button
                            className={`${
                              active
                                ? "bg-gray-400 text-white"
                                : "text-gray-900"
                            } group w-full items-center rounded-md px-2 py-2 text-sm text-center`}
                          >
                            About
                          </button>
                        </Link>
                      )}
                    </Menu.Item>
                  </div>
                  <div className="px-1 py-1 hover:bg-gray-400">
                    <Menu.Item>
                      {({ active }) => (
                        <Link href="/project">
                          <button
                            className={`${
                              active
                                ? "bg-gray-400 text-white"
                                : "text-gray-900"
                            } group w-full items-center rounded-md px-2 py-2 text-sm text-center`}
                          >
                            Projects
                          </button>
                        </Link>
                      )}
                    </Menu.Item>
                  </div>
                  <div className="px-1 py-1 hover:bg-gray-400">
                    <Menu.Item>
                      {({ active }) => (
                        <Link href="/contact">
                          <button
                            className={`${
                              active
                                ? "bg-gray-400 text-white"
                                : "text-gray-900"
                            } group w-full items-center rounded-md px-2 py-2 text-sm text-center`}
                          >
                            Contact
                          </button>
                        </Link>
                      )}
                    </Menu.Item>
                  </div>
                </Menu.Items>
              </Transition>
            </Menu>
          </div>
        </div>
        <div className="h-screen md:w-8/12 bg-[url('../public/laptop.jpg')] bg-cover bg-center"></div>
      </div>
    </div>
  );
}
